<?php

/*
 * Implements hook_form_FORM_ID_alter().
 *
 * Add a 'shippable' checkbox to the product type edit form.
 */
function commerce_shipment_fields_form_commerce_product_ui_product_type_form_alter(&$form, &$form_state, $form_id) {
  $form['product_type']['shippable'] = array(
    '#type' => 'checkbox',
    '#title' => t('This is a shippable product type.'),
    '#default_value' => $form_state['product_type']['shippable'],
  );
}
